# Generated by Django 5.2.4 on 2025-08-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('donations_raised', models.IntegerField(default=0)),
            ],
        ),
    ]
